project_name: jwt-hack

before:
  hooks:
  - go mod download

builds:
  -
    main: .
    binary: jwt-hack
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: hahwul
    name: jwt-hack

brews:
  -
    name: jwt-hack
    tap:
      owner: hahwul
      name: homebrew-jwt-hack
    url_template: "https://github.com/hahwul/jwt-hack/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: hahwul
      email: hahwul@gmail.com
    folder: Formula
    homepage: "https://www.hahwul.com"
    description: "jwt-hack is JWT hacking, security testing utility"
    test: |
      system "#{bin}/jwt-hack version"
    install: |
      bin.install "jwt-hack"
snapcrafts:
  -
    name: jwt-hack
    # Remember you need to `snapcraft login` first.
    publish: true
    summary: jwt-hack is JWT hacking, security testing utility
    description: jwt-hack is JWT hacking, security testing utility / support encode, decode, generate attack payloads and cracking mode(dict / bruteforce)
    grade: stable
    confinement: strict
    license: MIT
